export default [
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/1000",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/1000/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/1000/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/1000/events",
  "html_url": "https://github.com/Polymer/polymer/issues/1000",
  "id": 51165068,
  "number": 1000,
  "title": "Remember scroll position of selected page and prevent auto scrolling when selecting a other page.",
  "user": {
    "login": "gertcuykens",
    "id": 863731,
    "avatar_url": "https://avatars.githubusercontent.com/u/863731?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gertcuykens",
    "html_url": "https://github.com/gertcuykens",
    "followers_url": "https://api.github.com/users/gertcuykens/followers",
    "following_url": "https://api.github.com/users/gertcuykens/following{/other_user}",
    "gists_url": "https://api.github.com/users/gertcuykens/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gertcuykens/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gertcuykens/subscriptions",
    "organizations_url": "https://api.github.com/users/gertcuykens/orgs",
    "repos_url": "https://api.github.com/users/gertcuykens/repos",
    "events_url": "https://api.github.com/users/gertcuykens/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gertcuykens/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-12-06T01:20:06Z",
  "updated_at": "2014-12-06T01:32:08Z",
  "closed_at": null,
  "body": "http://sea-is-snow.appspot.com/\r\n\r\nStep1) Wait for the page to be loaded\r\nStep2) Scroll to the bottom\r\nStep3) When you are at the bottom select About us in the menu tab\r\nStep4) The page scrolls up automaticly, now click on the sis logo to go back\r\nStep5) Notice it is not at the bottom anymore\r\n\r\nThe auto scrolling is annoying, tel polymer to stop doing that and just restore the scroll position from the selected page without making me sea sick :P \r\n\r\nConsider them the same as browser tabs, you also definitely don't want them to change scroll position when you scroll in your current browser tab. Its against material design. Ok I made that last one up :) haha but still don't do it."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/999",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/999/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/999/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/999/events",
  "html_url": "https://github.com/Polymer/polymer/issues/999",
  "id": 51030547,
  "number": 999,
  "title": "Testing polymer in Intellij IDE Request ID=946019532871517420",
  "user": {
    "login": "gertcuykens",
    "id": 863731,
    "avatar_url": "https://avatars.githubusercontent.com/u/863731?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gertcuykens",
    "html_url": "https://github.com/gertcuykens",
    "followers_url": "https://api.github.com/users/gertcuykens/followers",
    "following_url": "https://api.github.com/users/gertcuykens/following{/other_user}",
    "gists_url": "https://api.github.com/users/gertcuykens/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gertcuykens/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gertcuykens/subscriptions",
    "organizations_url": "https://api.github.com/users/gertcuykens/orgs",
    "repos_url": "https://api.github.com/users/gertcuykens/repos",
    "events_url": "https://api.github.com/users/gertcuykens/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gertcuykens/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-12-04T21:20:16Z",
  "updated_at": "2014-12-04T21:25:59Z",
  "closed_at": null,
  "body": "I tried getting a free Intellij IDE for testing Polymer stuff but only you guys get one :-p This is just to let you know you can have a free license for polymer if interested.\r\n\r\n```text\r\nPolymer project qualifies for a free OS license of WebStorm, however we can only issue a license to the project's core team (https://github.com/orgs/Polymer/people). Please feel free to forward this message to them.\r\n\r\nKind regards,\r\nJulia Kuznetsova\r\nCommunity Support Coordinator\r\n```\r\n\r\nI already found some things that can be improved I am sure you can add a ton more things they can improve."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/998",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/998/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/998/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/998/events",
  "html_url": "https://github.com/Polymer/polymer/issues/998",
  "id": 51018754,
  "number": 998,
  "title": "Computed properties issue",
  "user": {
    "login": "malekpour",
    "id": 542968,
    "avatar_url": "https://avatars.githubusercontent.com/u/542968?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/malekpour",
    "html_url": "https://github.com/malekpour",
    "followers_url": "https://api.github.com/users/malekpour/followers",
    "following_url": "https://api.github.com/users/malekpour/following{/other_user}",
    "gists_url": "https://api.github.com/users/malekpour/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/malekpour/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/malekpour/subscriptions",
    "organizations_url": "https://api.github.com/users/malekpour/orgs",
    "repos_url": "https://api.github.com/users/malekpour/repos",
    "events_url": "https://api.github.com/users/malekpour/events{/privacy}",
    "received_events_url": "https://api.github.com/users/malekpour/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 1,
  "created_at": "2014-12-04T19:40:58Z",
  "updated_at": "2014-12-04T23:56:34Z",
  "closed_at": null,
  "body": "Computed properties and change detection does not work correctly for nested properties. In the following plunker by commenting line 53 polymer stops updating expression:\r\n\r\nhttp://plnkr.co/edit/PqVWRYSKk3Jcp87wlfZH?p=preview"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/996",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/996/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/996/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/996/events",
  "html_url": "https://github.com/Polymer/polymer/pull/996",
  "id": 51015670,
  "number": 996,
  "title": "Spelling correction.",
  "user": {
    "login": "germ13",
    "id": 146168,
    "avatar_url": "https://avatars.githubusercontent.com/u/146168?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/germ13",
    "html_url": "https://github.com/germ13",
    "followers_url": "https://api.github.com/users/germ13/followers",
    "following_url": "https://api.github.com/users/germ13/following{/other_user}",
    "gists_url": "https://api.github.com/users/germ13/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/germ13/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/germ13/subscriptions",
    "organizations_url": "https://api.github.com/users/germ13/orgs",
    "repos_url": "https://api.github.com/users/germ13/repos",
    "events_url": "https://api.github.com/users/germ13/events{/privacy}",
    "received_events_url": "https://api.github.com/users/germ13/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 1,
  "created_at": "2014-12-04T19:14:43Z",
  "updated_at": "2014-12-04T19:52:52Z",
  "closed_at": null,
  "pull_request": {
    "url": "https://api.github.com/repos/Polymer/polymer/pulls/996",
    "html_url": "https://github.com/Polymer/polymer/pull/996",
    "diff_url": "https://github.com/Polymer/polymer/pull/996.diff",
    "patch_url": "https://github.com/Polymer/polymer/pull/996.patch"
  },
  "body": ""
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/995",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/995/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/995/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/995/events",
  "html_url": "https://github.com/Polymer/polymer/issues/995",
  "id": 50989592,
  "number": 995,
  "title": "layout test is broken in FF 34",
  "user": {
    "login": "jakemac53",
    "id": 984921,
    "avatar_url": "https://avatars.githubusercontent.com/u/984921?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jakemac53",
    "html_url": "https://github.com/jakemac53",
    "followers_url": "https://api.github.com/users/jakemac53/followers",
    "following_url": "https://api.github.com/users/jakemac53/following{/other_user}",
    "gists_url": "https://api.github.com/users/jakemac53/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jakemac53/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jakemac53/subscriptions",
    "organizations_url": "https://api.github.com/users/jakemac53/orgs",
    "repos_url": "https://api.github.com/users/jakemac53/repos",
    "events_url": "https://api.github.com/users/jakemac53/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jakemac53/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 4,
  "created_at": "2014-12-04T15:38:14Z",
  "updated_at": "2014-12-04T16:17:24Z",
  "closed_at": null,
  "body": "https://github.com/Polymer/polymer/blob/master/test/html/layout.html fails in FF 34, gives `AssertionError: unsized container: vertical flex items have no intrinsic height: expected '19px' to equal '0px'`"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/993",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/993/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/993/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/993/events",
  "html_url": "https://github.com/Polymer/polymer/issues/993",
  "id": 50906619,
  "number": 993,
  "title": "core-overlay not working on firefox 34",
  "user": {
    "login": "dgrasberger",
    "id": 6146810,
    "avatar_url": "https://avatars.githubusercontent.com/u/6146810?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dgrasberger",
    "html_url": "https://github.com/dgrasberger",
    "followers_url": "https://api.github.com/users/dgrasberger/followers",
    "following_url": "https://api.github.com/users/dgrasberger/following{/other_user}",
    "gists_url": "https://api.github.com/users/dgrasberger/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dgrasberger/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dgrasberger/subscriptions",
    "organizations_url": "https://api.github.com/users/dgrasberger/orgs",
    "repos_url": "https://api.github.com/users/dgrasberger/repos",
    "events_url": "https://api.github.com/users/dgrasberger/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dgrasberger/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-12-03T23:12:24Z",
  "updated_at": "2014-12-03T23:12:24Z",
  "closed_at": null,
  "body": "Using .51 and noticed the problem.  Pointed firefox at demo page (https://www.polymer-project.org/components/core-overlay/demo.html -- try it to reproduce the bug) and overlay never opened -- my experience was that overlay would open but not close."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/990",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/990/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/990/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/990/events",
  "html_url": "https://github.com/Polymer/polymer/issues/990",
  "id": 50819181,
  "number": 990,
  "title": "cloneNode doesn't clone changed attribute",
  "user": {
    "login": "shycherry",
    "id": 2857848,
    "avatar_url": "https://avatars.githubusercontent.com/u/2857848?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/shycherry",
    "html_url": "https://github.com/shycherry",
    "followers_url": "https://api.github.com/users/shycherry/followers",
    "following_url": "https://api.github.com/users/shycherry/following{/other_user}",
    "gists_url": "https://api.github.com/users/shycherry/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/shycherry/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/shycherry/subscriptions",
    "organizations_url": "https://api.github.com/users/shycherry/orgs",
    "repos_url": "https://api.github.com/users/shycherry/repos",
    "events_url": "https://api.github.com/users/shycherry/events{/privacy}",
    "received_events_url": "https://api.github.com/users/shycherry/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 4,
  "created_at": "2014-12-03T10:43:17Z",
  "updated_at": "2014-12-03T17:57:39Z",
  "closed_at": null,
  "body": "Hello Polymer team !\r\nPlease take a look at this codepen :\r\nhttp://codepen.io/anon/pen/LEpBeE\r\n\r\nChange the input value, see in the console that element's command attribute is changed.\r\nClick clone : the cloned element's command attribute stay as if it was unchanged.\r\n\r\nWhy such behavior ?\r\nThank you !"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/989",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/989/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/989/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/989/events",
  "html_url": "https://github.com/Polymer/polymer/issues/989",
  "id": 50765054,
  "number": 989,
  "title": "On android chrome: need to tap paper-input twice to open on-screen-kb",
  "user": {
    "login": "snickell",
    "id": 223277,
    "avatar_url": "https://avatars.githubusercontent.com/u/223277?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/snickell",
    "html_url": "https://github.com/snickell",
    "followers_url": "https://api.github.com/users/snickell/followers",
    "following_url": "https://api.github.com/users/snickell/following{/other_user}",
    "gists_url": "https://api.github.com/users/snickell/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/snickell/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/snickell/subscriptions",
    "organizations_url": "https://api.github.com/users/snickell/orgs",
    "repos_url": "https://api.github.com/users/snickell/repos",
    "events_url": "https://api.github.com/users/snickell/events{/privacy}",
    "received_events_url": "https://api.github.com/users/snickell/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-12-03T02:08:27Z",
  "updated_at": "2014-12-03T02:08:27Z",
  "closed_at": null,
  "body": "Expected: tapping on a paper-input will bring up the android on screen keyboard\r\nActual: first tap focuses the paper-input (cursor blinks), but you have to tap a second time to bring up the keyboard"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/987",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/987/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/987/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/987/events",
  "html_url": "https://github.com/Polymer/polymer/pull/987",
  "id": 50600111,
  "number": 987,
  "title": "[0.8] Clean up import dependencies to avoid implicit dependencies.",
  "user": {
    "login": "nevir",
    "id": 41373,
    "avatar_url": "https://avatars.githubusercontent.com/u/41373?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nevir",
    "html_url": "https://github.com/nevir",
    "followers_url": "https://api.github.com/users/nevir/followers",
    "following_url": "https://api.github.com/users/nevir/following{/other_user}",
    "gists_url": "https://api.github.com/users/nevir/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nevir/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nevir/subscriptions",
    "organizations_url": "https://api.github.com/users/nevir/orgs",
    "repos_url": "https://api.github.com/users/nevir/repos",
    "events_url": "https://api.github.com/users/nevir/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nevir/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-12-02T01:03:16Z",
  "updated_at": "2014-12-02T01:12:18Z",
  "closed_at": null,
  "pull_request": {
    "url": "https://api.github.com/repos/Polymer/polymer/pulls/987",
    "html_url": "https://github.com/Polymer/polymer/pull/987",
    "diff_url": "https://github.com/Polymer/polymer/pull/987.diff",
    "patch_url": "https://github.com/Polymer/polymer/pull/987.patch"
  },
  "body": "Main intent here is to allow for piecemeal importing of features (aka the unit tests).\r\n\r\n(also sneaking in whitespace normalization)"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/986",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/986/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/986/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/986/events",
  "html_url": "https://github.com/Polymer/polymer/issues/986",
  "id": 50527613,
  "number": 986,
  "title": "No field view on iOS 8",
  "user": {
    "login": "RubensRainelli",
    "id": 9963182,
    "avatar_url": "https://avatars.githubusercontent.com/u/9963182?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/RubensRainelli",
    "html_url": "https://github.com/RubensRainelli",
    "followers_url": "https://api.github.com/users/RubensRainelli/followers",
    "following_url": "https://api.github.com/users/RubensRainelli/following{/other_user}",
    "gists_url": "https://api.github.com/users/RubensRainelli/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/RubensRainelli/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/RubensRainelli/subscriptions",
    "organizations_url": "https://api.github.com/users/RubensRainelli/orgs",
    "repos_url": "https://api.github.com/users/RubensRainelli/repos",
    "events_url": "https://api.github.com/users/RubensRainelli/events{/privacy}",
    "received_events_url": "https://api.github.com/users/RubensRainelli/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 9,
  "created_at": "2014-12-01T14:10:56Z",
  "updated_at": "2014-12-05T19:50:45Z",
  "closed_at": null,
  "body": "In Safari on iOS 8 it's not vieweable the text fields, please consider to fix this incompatibility."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/985",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/985/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/985/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/985/events",
  "html_url": "https://github.com/Polymer/polymer/pull/985",
  "id": 50488099,
  "number": 985,
  "title": "[0.8] more-feature supporting WebAnimations",
  "user": {
    "login": "nevir",
    "id": 41373,
    "avatar_url": "https://avatars.githubusercontent.com/u/41373?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nevir",
    "html_url": "https://github.com/nevir",
    "followers_url": "https://api.github.com/users/nevir/followers",
    "following_url": "https://api.github.com/users/nevir/following{/other_user}",
    "gists_url": "https://api.github.com/users/nevir/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nevir/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nevir/subscriptions",
    "organizations_url": "https://api.github.com/users/nevir/orgs",
    "repos_url": "https://api.github.com/users/nevir/repos",
    "events_url": "https://api.github.com/users/nevir/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nevir/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-12-01T05:03:58Z",
  "updated_at": "2014-12-02T04:01:48Z",
  "closed_at": null,
  "pull_request": {
    "url": "https://api.github.com/repos/Polymer/polymer/pulls/985",
    "html_url": "https://github.com/Polymer/polymer/pull/985",
    "diff_url": "https://github.com/Polymer/polymer/pull/985.diff",
    "patch_url": "https://github.com/Polymer/polymer/pull/985.patch"
  },
  "body": "Hopefully makes web animations a little easier to declare within polymer elements.\r\n\r\nNote that this gives us all the same shorthand behavior as `element.animate` (i.e. groups). For the next iteration, I want to tackle shorthands for groups and sequences (which potentially have different target selectors)"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/983",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/983/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/983/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/983/events",
  "html_url": "https://github.com/Polymer/polymer/issues/983",
  "id": 50458927,
  "number": 983,
  "title": "auto assign {{-attribute}} instead of writing  attribute=\"{{attribute}}\"",
  "user": {
    "login": "gertcuykens",
    "id": 863731,
    "avatar_url": "https://avatars.githubusercontent.com/u/863731?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gertcuykens",
    "html_url": "https://github.com/gertcuykens",
    "followers_url": "https://api.github.com/users/gertcuykens/followers",
    "following_url": "https://api.github.com/users/gertcuykens/following{/other_user}",
    "gists_url": "https://api.github.com/users/gertcuykens/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gertcuykens/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gertcuykens/subscriptions",
    "organizations_url": "https://api.github.com/users/gertcuykens/orgs",
    "repos_url": "https://api.github.com/users/gertcuykens/repos",
    "events_url": "https://api.github.com/users/gertcuykens/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gertcuykens/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-30T14:13:14Z",
  "updated_at": "2014-11-30T14:13:14Z",
  "closed_at": null,
  "body": "Example \r\n```<tiedot-service id=\"service\" jwt=\"{{jwt}}\" url=\"{{url}}\" json=\"{{json}}\"></tiedot-service>```\r\n\r\nEquals \r\n```<tiedot-service id=\"service\" {{-jwt}} {{-url}} {{-json}}></tiedot-service>```\r\n\r\n\r\n"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/982",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/982/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/982/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/982/events",
  "html_url": "https://github.com/Polymer/polymer/issues/982",
  "id": 50458157,
  "number": 982,
  "title": "Polymer text input fields are not registered by \"Vimium\" as a text input field",
  "user": {
    "login": "kmelkon",
    "id": 1743113,
    "avatar_url": "https://avatars.githubusercontent.com/u/1743113?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kmelkon",
    "html_url": "https://github.com/kmelkon",
    "followers_url": "https://api.github.com/users/kmelkon/followers",
    "following_url": "https://api.github.com/users/kmelkon/following{/other_user}",
    "gists_url": "https://api.github.com/users/kmelkon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kmelkon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kmelkon/subscriptions",
    "organizations_url": "https://api.github.com/users/kmelkon/orgs",
    "repos_url": "https://api.github.com/users/kmelkon/repos",
    "events_url": "https://api.github.com/users/kmelkon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kmelkon/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-30T13:41:13Z",
  "updated_at": "2014-11-30T13:41:13Z",
  "closed_at": null,
  "body": "I'm using Chrome Version 38.0.2125.122 on Ubuntu GNOME 14.10 (64bit), and I have an extension called Vimium for emulating some of Vim functionality in Chrome.\r\n\r\nwhen I'm writing in a text input field the extension stops listening for the specified hotkeys, unless it's a field in the shadow DOM.\r\n\r\nAny solution other than disabling the extension on pages using Polymer/web-components?"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/980",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/980/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/980/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/980/events",
  "html_url": "https://github.com/Polymer/polymer/issues/980",
  "id": 50435553,
  "number": 980,
  "title": "Wrong Bindings types documentation",
  "user": {
    "login": "brunocascio",
    "id": 2397875,
    "avatar_url": "https://avatars.githubusercontent.com/u/2397875?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/brunocascio",
    "html_url": "https://github.com/brunocascio",
    "followers_url": "https://api.github.com/users/brunocascio/followers",
    "following_url": "https://api.github.com/users/brunocascio/following{/other_user}",
    "gists_url": "https://api.github.com/users/brunocascio/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/brunocascio/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/brunocascio/subscriptions",
    "organizations_url": "https://api.github.com/users/brunocascio/orgs",
    "repos_url": "https://api.github.com/users/brunocascio/repos",
    "events_url": "https://api.github.com/users/brunocascio/events{/privacy}",
    "received_events_url": "https://api.github.com/users/brunocascio/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 1,
  "created_at": "2014-11-29T19:59:35Z",
  "updated_at": "2014-11-29T20:18:35Z",
  "closed_at": null,
  "body": "https://www.polymer-project.org/docs/polymer/binding-types.html\r\n\r\nIs correct this?\r\n![captura de pantalla de 2014-11-29 16 58 34](https://cloud.githubusercontent.com/assets/2397875/5235632/fd34a398-77e8-11e4-9918-45dc98b78173.png)\r\n\r\nMaybe: \r\n\r\n```\r\n<template>\r\n  <template>\r\n    <template repeat=\"{{items}}\" id=\"t\">\r\n      <li>{{name}}</li>\r\n    </template>\r\n    <ul>\r\n      <template ref=\"t\" repeat=\"{{children}}\"></template>\r\n    </ul>\r\n  </template>\r\n</template>\r\n```"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/979",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/979/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/979/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/979/events",
  "html_url": "https://github.com/Polymer/polymer/issues/979",
  "id": 50434818,
  "number": 979,
  "title": "A way to manually recompute computed properties",
  "user": {
    "login": "thedeeno",
    "id": 84087,
    "avatar_url": "https://avatars.githubusercontent.com/u/84087?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/thedeeno",
    "html_url": "https://github.com/thedeeno",
    "followers_url": "https://api.github.com/users/thedeeno/followers",
    "following_url": "https://api.github.com/users/thedeeno/following{/other_user}",
    "gists_url": "https://api.github.com/users/thedeeno/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/thedeeno/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/thedeeno/subscriptions",
    "organizations_url": "https://api.github.com/users/thedeeno/orgs",
    "repos_url": "https://api.github.com/users/thedeeno/repos",
    "events_url": "https://api.github.com/users/thedeeno/events{/privacy}",
    "received_events_url": "https://api.github.com/users/thedeeno/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-29T19:29:19Z",
  "updated_at": "2014-11-29T19:54:08Z",
  "closed_at": null,
  "body": "I'm not sure this if this is undocumented or unsupported. \r\n\r\nGiven this custom element\r\n\r\n```\r\nPolymer({\r\n  name: 'dane',\r\n\r\n  computed: {\r\n    message: 'greet(name)'\r\n  },\r\n\r\n  greet: function(name) {\r\n    return 'hello ' + name + Date.now();\r\n  }\r\n})\r\n```\r\n\r\nWhen I change `name` polymer automatically recomputes `message`. Awesome. But is there a way to manually recompute `message` without changing `name`?"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/978",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/978/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/978/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/978/events",
  "html_url": "https://github.com/Polymer/polymer/issues/978",
  "id": 50423225,
  "number": 978,
  "title": "Topeka example takes > 30 seconds to load on smartphones",
  "user": {
    "login": "richieb",
    "id": 80035,
    "avatar_url": "https://avatars.githubusercontent.com/u/80035?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/richieb",
    "html_url": "https://github.com/richieb",
    "followers_url": "https://api.github.com/users/richieb/followers",
    "following_url": "https://api.github.com/users/richieb/following{/other_user}",
    "gists_url": "https://api.github.com/users/richieb/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/richieb/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/richieb/subscriptions",
    "organizations_url": "https://api.github.com/users/richieb/orgs",
    "repos_url": "https://api.github.com/users/richieb/repos",
    "events_url": "https://api.github.com/users/richieb/events{/privacy}",
    "received_events_url": "https://api.github.com/users/richieb/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 1,
  "created_at": "2014-11-29T11:29:56Z",
  "updated_at": "2014-11-29T14:10:34Z",
  "closed_at": null,
  "body": "I just tested the latest version of Topeka (on master), and it takes more than 30 seconds to load on both iOS 8 (Safari mobile on iPad) and Android (Note 4, both Chrome and Samsung's browser).\r\n\r\nI am about to use Polymer for my next project, but I want to make sure it will load faster than it loading now on smartphones."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/975",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/975/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/975/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/975/events",
  "html_url": "https://github.com/Polymer/polymer/issues/975",
  "id": 50411092,
  "number": 975,
  "title": "Issue with polymer on iOS 8",
  "user": {
    "login": "MeloJR",
    "id": 5193005,
    "avatar_url": "https://avatars.githubusercontent.com/u/5193005?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/MeloJR",
    "html_url": "https://github.com/MeloJR",
    "followers_url": "https://api.github.com/users/MeloJR/followers",
    "following_url": "https://api.github.com/users/MeloJR/following{/other_user}",
    "gists_url": "https://api.github.com/users/MeloJR/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/MeloJR/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/MeloJR/subscriptions",
    "organizations_url": "https://api.github.com/users/MeloJR/orgs",
    "repos_url": "https://api.github.com/users/MeloJR/repos",
    "events_url": "https://api.github.com/users/MeloJR/events{/privacy}",
    "received_events_url": "https://api.github.com/users/MeloJR/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 3,
  "created_at": "2014-11-29T01:17:51Z",
  "updated_at": "2014-12-02T18:37:32Z",
  "closed_at": null,
  "body": "Both Safari and Chrome fail to display a web app written in polymer in an iPhone with iOS 8.\r\n\r\nThe same web app fails as well when you try to display it using the native browser Apache Cordova launches in its applications.\r\n\r\n\r\n"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/974",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/974/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/974/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/974/events",
  "html_url": "https://github.com/Polymer/polymer/issues/974",
  "id": 50408448,
  "number": 974,
  "title": "Paper Elements Accessibility ",
  "user": {
    "login": "rodrigoprestesmachado",
    "id": 7852824,
    "avatar_url": "https://avatars.githubusercontent.com/u/7852824?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rodrigoprestesmachado",
    "html_url": "https://github.com/rodrigoprestesmachado",
    "followers_url": "https://api.github.com/users/rodrigoprestesmachado/followers",
    "following_url": "https://api.github.com/users/rodrigoprestesmachado/following{/other_user}",
    "gists_url": "https://api.github.com/users/rodrigoprestesmachado/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rodrigoprestesmachado/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rodrigoprestesmachado/subscriptions",
    "organizations_url": "https://api.github.com/users/rodrigoprestesmachado/orgs",
    "repos_url": "https://api.github.com/users/rodrigoprestesmachado/repos",
    "events_url": "https://api.github.com/users/rodrigoprestesmachado/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rodrigoprestesmachado/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 2,
  "created_at": "2014-11-28T23:28:17Z",
  "updated_at": "2014-11-29T11:42:00Z",
  "closed_at": null,
  "body": "Hello,\r\n\r\nI was trying to use Polymer in a project but I realize that some Paper Elements does not implement appropriated WAI-ARIA specification. Do you have plans to add this feature in core and paper elements?\r\n\r\nBest regards,\r\nRodrigo\r\n\r\n\r\n"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/972",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/972/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/972/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/972/events",
  "html_url": "https://github.com/Polymer/polymer/issues/972",
  "id": 50318216,
  "number": 972,
  "title": "Make it easy to spot missing-import errors",
  "user": {
    "login": "tommie",
    "id": 216382,
    "avatar_url": "https://avatars.githubusercontent.com/u/216382?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tommie",
    "html_url": "https://github.com/tommie",
    "followers_url": "https://api.github.com/users/tommie/followers",
    "following_url": "https://api.github.com/users/tommie/following{/other_user}",
    "gists_url": "https://api.github.com/users/tommie/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tommie/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tommie/subscriptions",
    "organizations_url": "https://api.github.com/users/tommie/orgs",
    "repos_url": "https://api.github.com/users/tommie/repos",
    "events_url": "https://api.github.com/users/tommie/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tommie/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 4,
  "created_at": "2014-11-27T19:10:11Z",
  "updated_at": "2014-11-27T22:04:55Z",
  "closed_at": null,
  "body": "One type of error is fairly common with Polymer; forgetting to import a component definition. In most programming languages, this results in an \"undefined\" error, but since Custom components allows registering after the fact, there is no clue. And the element is simply rendered as nothing.\r\n\r\nIt would be nice to have a debug/linting mode where unresolved elements are printed to the console, or highlighted in the DOM somehow. It could be triggered by a timer set at page load to account somewhat for delayed registrations. Or in \"polymer-ready\". The output would be just a list of unresolved elements (and possibly their source location, if possible.)\r\n\r\nBTW, this is somewhat similar to the problem of printing error messages for unhandled exception in Twisted Python's Deferreds... They do it in the destructor, so if nothing has handled the exception, it will likely get shown at some point."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/971",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/971/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/971/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/971/events",
  "html_url": "https://github.com/Polymer/polymer/issues/971",
  "id": 50311297,
  "number": 971,
  "title": "Responsive image doesn't render on page load in Chrome, renders on opening dev tools",
  "user": {
    "login": "atomikolex",
    "id": 9979190,
    "avatar_url": "https://avatars.githubusercontent.com/u/9979190?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/atomikolex",
    "html_url": "https://github.com/atomikolex",
    "followers_url": "https://api.github.com/users/atomikolex/followers",
    "following_url": "https://api.github.com/users/atomikolex/following{/other_user}",
    "gists_url": "https://api.github.com/users/atomikolex/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/atomikolex/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/atomikolex/subscriptions",
    "organizations_url": "https://api.github.com/users/atomikolex/orgs",
    "repos_url": "https://api.github.com/users/atomikolex/repos",
    "events_url": "https://api.github.com/users/atomikolex/events{/privacy}",
    "received_events_url": "https://api.github.com/users/atomikolex/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-27T17:12:10Z",
  "updated_at": "2014-12-01T13:03:19Z",
  "closed_at": null,
  "body": "An img with srcset and sizes attributes inside a polymer template won't render on page load, but only after dev tools are opened.\r\nThis bug is limited to Chrome and didn't occur prior to version 39."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/969",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/969/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/969/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/969/events",
  "html_url": "https://github.com/Polymer/polymer/issues/969",
  "id": 50198696,
  "number": 969,
  "title": "Core-header-panel  Uncaught SyntaxError: Unexpected token (",
  "user": {
    "login": "fredpedro",
    "id": 8825337,
    "avatar_url": "https://avatars.githubusercontent.com/u/8825337?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/fredpedro",
    "html_url": "https://github.com/fredpedro",
    "followers_url": "https://api.github.com/users/fredpedro/followers",
    "following_url": "https://api.github.com/users/fredpedro/following{/other_user}",
    "gists_url": "https://api.github.com/users/fredpedro/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/fredpedro/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/fredpedro/subscriptions",
    "organizations_url": "https://api.github.com/users/fredpedro/orgs",
    "repos_url": "https://api.github.com/users/fredpedro/repos",
    "events_url": "https://api.github.com/users/fredpedro/events{/privacy}",
    "received_events_url": "https://api.github.com/users/fredpedro/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-26T16:24:23Z",
  "updated_at": "2014-11-26T16:24:23Z",
  "closed_at": null,
  "body": "When i tried to insert into the scrip tag,\r\n\r\nscrollHandler: function(event) {\r\n  var scroller = event.detail.target;\r\n  console.log(scroller.scrollTop);\r\n}\r\n\r\nIt create an error that says \"Uncaught SyntaxError: Unexpected token (\""
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/966",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/966/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/966/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/966/events",
  "html_url": "https://github.com/Polymer/polymer/issues/966",
  "id": 50102717,
  "number": 966,
  "title": "Template Binding outside polymer-element does not work with 0.8-preview",
  "user": {
    "login": "tomalec",
    "id": 17435,
    "avatar_url": "https://avatars.githubusercontent.com/u/17435?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tomalec",
    "html_url": "https://github.com/tomalec",
    "followers_url": "https://api.github.com/users/tomalec/followers",
    "following_url": "https://api.github.com/users/tomalec/following{/other_user}",
    "gists_url": "https://api.github.com/users/tomalec/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tomalec/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tomalec/subscriptions",
    "organizations_url": "https://api.github.com/users/tomalec/orgs",
    "repos_url": "https://api.github.com/users/tomalec/repos",
    "events_url": "https://api.github.com/users/tomalec/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tomalec/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-26T00:19:47Z",
  "updated_at": "2014-11-26T00:19:47Z",
  "closed_at": null,
  "body": "I am not sure if it is a bug, I cannot enable some features, or Template Binding feature for templates outside polymer-element's ShadowDOM will be removed in 0.8.\r\n\r\nMy test case is here http://jsfiddle.net/tomalec/31tLeL37/\r\n```html\r\n<template id=\"myTempl\" bind>\r\n Hello {{who}}!\r\n</template>\r\n```\r\n\r\nImporting additional [features](https://github.com/Polymer/polymer/tree/0.8-preview/src/features) did not help, I have also tried adding them to particular `<template>` node, with no luck.\r\n\r\nI hope \"The heavyweight binding system will now be opt-in\" does not mean it will not be able to support non-polymer templates at all, as many of my apps, and individual Custom Elements (some almost-production) uses it extensively."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/964",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/964/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/964/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/964/events",
  "html_url": "https://github.com/Polymer/polymer/pull/964",
  "id": 50031532,
  "number": 964,
  "title": "Fix wrong HTML Imports loaded callback in 'using'",
  "user": {
    "login": "nelsonsilva",
    "id": 6028,
    "avatar_url": "https://avatars.githubusercontent.com/u/6028?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nelsonsilva",
    "html_url": "https://github.com/nelsonsilva",
    "followers_url": "https://api.github.com/users/nelsonsilva/followers",
    "following_url": "https://api.github.com/users/nelsonsilva/following{/other_user}",
    "gists_url": "https://api.github.com/users/nelsonsilva/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nelsonsilva/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nelsonsilva/subscriptions",
    "organizations_url": "https://api.github.com/users/nelsonsilva/orgs",
    "repos_url": "https://api.github.com/users/nelsonsilva/repos",
    "events_url": "https://api.github.com/users/nelsonsilva/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nelsonsilva/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-25T14:14:19Z",
  "updated_at": "2014-11-25T14:14:19Z",
  "closed_at": null,
  "pull_request": {
    "url": "https://api.github.com/repos/Polymer/polymer/pulls/964",
    "html_url": "https://github.com/Polymer/polymer/pull/964",
    "diff_url": "https://github.com/Polymer/polymer/pull/964.diff",
    "patch_url": "https://github.com/Polymer/polymer/pull/964.patch"
  },
  "body": "HTMLImports.whenImportsReady was renamed to whenReady."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/963",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/963/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/963/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/963/events",
  "html_url": "https://github.com/Polymer/polymer/issues/963",
  "id": 49981795,
  "number": 963,
  "title": "[unresolved] does not work as expected on elements inside auto-binding template",
  "user": {
    "login": "ebidel",
    "id": 238208,
    "avatar_url": "https://avatars.githubusercontent.com/u/238208?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ebidel",
    "html_url": "https://github.com/ebidel",
    "followers_url": "https://api.github.com/users/ebidel/followers",
    "following_url": "https://api.github.com/users/ebidel/following{/other_user}",
    "gists_url": "https://api.github.com/users/ebidel/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ebidel/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ebidel/subscriptions",
    "organizations_url": "https://api.github.com/users/ebidel/orgs",
    "repos_url": "https://api.github.com/users/ebidel/repos",
    "events_url": "https://api.github.com/users/ebidel/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ebidel/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-25T06:33:24Z",
  "updated_at": "2014-11-25T06:33:24Z",
  "closed_at": null,
  "body": "Test: http://jsbin.com/yijusuqahe/1/edit?html,output\r\n\r\nBoth elements should fade in, but only the one outside of the auto-binding does. Presumably this is because `polymer-ready` happens before the template is stamped.\r\n\r\n:santa: "
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/961",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/961/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/961/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/961/events",
  "html_url": "https://github.com/Polymer/polymer/issues/961",
  "id": 49909978,
  "number": 961,
  "title": "Manual handling of resolving components resolving",
  "user": {
    "login": "davej",
    "id": 26971,
    "avatar_url": "https://avatars.githubusercontent.com/u/26971?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/davej",
    "html_url": "https://github.com/davej",
    "followers_url": "https://api.github.com/users/davej/followers",
    "following_url": "https://api.github.com/users/davej/following{/other_user}",
    "gists_url": "https://api.github.com/users/davej/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/davej/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/davej/subscriptions",
    "organizations_url": "https://api.github.com/users/davej/orgs",
    "repos_url": "https://api.github.com/users/davej/repos",
    "events_url": "https://api.github.com/users/davej/events{/privacy}",
    "received_events_url": "https://api.github.com/users/davej/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-24T16:24:03Z",
  "updated_at": "2014-11-24T16:24:03Z",
  "closed_at": null,
  "body": "I want to be able to manually handle when my component is marked as resolved.\r\n\r\nIn my specific case I want to delay resolution of the component until a background image has loaded. I am able to do this by creating my own custom attribute `image-loading` but I feel it would make more sense to make use of the `unresolved` attribute, since it is already widely used."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/960",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/960/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/960/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/960/events",
  "html_url": "https://github.com/Polymer/polymer/issues/960",
  "id": 49903104,
  "number": 960,
  "title": "Manual handling of resolving components resolving",
  "user": {
    "login": "davej",
    "id": 26971,
    "avatar_url": "https://avatars.githubusercontent.com/u/26971?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/davej",
    "html_url": "https://github.com/davej",
    "followers_url": "https://api.github.com/users/davej/followers",
    "following_url": "https://api.github.com/users/davej/following{/other_user}",
    "gists_url": "https://api.github.com/users/davej/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/davej/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/davej/subscriptions",
    "organizations_url": "https://api.github.com/users/davej/orgs",
    "repos_url": "https://api.github.com/users/davej/repos",
    "events_url": "https://api.github.com/users/davej/events{/privacy}",
    "received_events_url": "https://api.github.com/users/davej/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-24T15:39:39Z",
  "updated_at": "2014-11-24T15:39:39Z",
  "closed_at": null,
  "body": "I want to be able to manually handle when my component is marked as resolved.\r\n\r\nIn my specific case I want to delay resolution of the component until a background image has loaded. I am able to do this by creating my own custom attribute `image-loading` but I feel it would make more sense to make use of the `unresolved` attribute, since it is already widely used."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/959",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/959/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/959/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/959/events",
  "html_url": "https://github.com/Polymer/polymer/issues/959",
  "id": 49837454,
  "number": 959,
  "title": "<meta name=\"layout\" content=\"polymer or some other layout2\">",
  "user": {
    "login": "gertcuykens",
    "id": 863731,
    "avatar_url": "https://avatars.githubusercontent.com/u/863731?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gertcuykens",
    "html_url": "https://github.com/gertcuykens",
    "followers_url": "https://api.github.com/users/gertcuykens/followers",
    "following_url": "https://api.github.com/users/gertcuykens/following{/other_user}",
    "gists_url": "https://api.github.com/users/gertcuykens/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gertcuykens/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gertcuykens/subscriptions",
    "organizations_url": "https://api.github.com/users/gertcuykens/orgs",
    "repos_url": "https://api.github.com/users/gertcuykens/repos",
    "events_url": "https://api.github.com/users/gertcuykens/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gertcuykens/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 2,
  "created_at": "2014-11-23T20:15:34Z",
  "updated_at": "2014-11-24T00:49:04Z",
  "closed_at": null,
  "body": "https://www.polymer-project.org/docs/polymer/layout-attrs.html\r\n\r\nWhy not `horizontal` or `vertical` instead of `layout horizontal` `layout vertical`?\r\n\r\nIf layout just enables flex then vertical and horizontal can enable that too?\r\n\r\n\r\n"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/958",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/958/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/958/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/958/events",
  "html_url": "https://github.com/Polymer/polymer/issues/958",
  "id": 49826863,
  "number": 958,
  "title": "Cyclic dependencies in bower config",
  "user": {
    "login": "kavika13",
    "id": 439185,
    "avatar_url": "https://avatars.githubusercontent.com/u/439185?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kavika13",
    "html_url": "https://github.com/kavika13",
    "followers_url": "https://api.github.com/users/kavika13/followers",
    "following_url": "https://api.github.com/users/kavika13/following{/other_user}",
    "gists_url": "https://api.github.com/users/kavika13/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kavika13/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kavika13/subscriptions",
    "organizations_url": "https://api.github.com/users/kavika13/orgs",
    "repos_url": "https://api.github.com/users/kavika13/repos",
    "events_url": "https://api.github.com/users/kavika13/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kavika13/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 3,
  "created_at": "2014-11-23T14:19:42Z",
  "updated_at": "2014-11-24T00:23:14Z",
  "closed_at": null,
  "body": "I'm new to bower and to Polymer, so apologies if this is wrong/boneheaded :)\r\n\r\n* Polymer/polymer depends on Polymer/core-component-page\r\n* Polymer/core-component-page depends on Polymer/polymer\r\n\r\nDoes this seem like a cyclic dependency, and should it be fixed?\r\n\r\nI found this problem when trying to use http://brunch.io. I got a stack overflow (`brunch/node_modules/read-components/index.js:0` `RangeError: Maximum call stack size exceeded`) after including Polymer.\r\n\r\nI fixed it by breaking the dependency using the `overrides` feature to set `core-component-page`'s dependencies to remove `Polymer/polymer`. Here's what my `overrides` ended up looking like after addressing all the problems I found:\r\n\r\n    \"overrides\": {\r\n      \"polymer\": {\r\n        \"main\": \"polymer.html\",\r\n        \"dependencies\": {}\r\n      },\r\n      \"core-component-page\": { \"main\": \"core-component-page.html\" }\r\n    }\r\n"
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/953",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/953/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/953/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/953/events",
  "html_url": "https://github.com/Polymer/polymer/issues/953",
  "id": 49758243,
  "number": 953,
  "title": "paper-input element not working in Chrome on iOS8.1",
  "user": {
    "login": "lihan",
    "id": 655051,
    "avatar_url": "https://avatars.githubusercontent.com/u/655051?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/lihan",
    "html_url": "https://github.com/lihan",
    "followers_url": "https://api.github.com/users/lihan/followers",
    "following_url": "https://api.github.com/users/lihan/following{/other_user}",
    "gists_url": "https://api.github.com/users/lihan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/lihan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/lihan/subscriptions",
    "organizations_url": "https://api.github.com/users/lihan/orgs",
    "repos_url": "https://api.github.com/users/lihan/repos",
    "events_url": "https://api.github.com/users/lihan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/lihan/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2014-11-21T22:54:20Z",
  "updated_at": "2014-11-21T22:54:20Z",
  "closed_at": null,
  "body": "Open [paper-input demo page](https://www.polymer-project.org/components/paper-input/demo.html) in Chrome on iOS8.1, you will see none of the input control works. This control however works in mobile Safari from iOS 8.1."
},
{
  "url": "https://api.github.com/repos/Polymer/polymer/issues/952",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/952/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/952/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/952/events",
  "html_url": "https://github.com/Polymer/polymer/issues/952",
  "id": 49721847,
  "number": 952,
  "title": "Performance in Firefox",
  "user": {
    "login": "Mikanoshi",
    "id": 5113439,
    "avatar_url": "https://avatars.githubusercontent.com/u/5113439?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Mikanoshi",
    "html_url": "https://github.com/Mikanoshi",
    "followers_url": "https://api.github.com/users/Mikanoshi/followers",
    "following_url": "https://api.github.com/users/Mikanoshi/following{/other_user}",
    "gists_url": "https://api.github.com/users/Mikanoshi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Mikanoshi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Mikanoshi/subscriptions",
    "organizations_url": "https://api.github.com/users/Mikanoshi/orgs",
    "repos_url": "https://api.github.com/users/Mikanoshi/repos",
    "events_url": "https://api.github.com/users/Mikanoshi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Mikanoshi/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 2,
  "created_at": "2014-11-21T17:06:28Z",
  "updated_at": "2014-11-24T00:53:42Z",
  "closed_at": null,
  "body": "I need to create ~700 paper-input fields, it takes 2-3 seconds in Chrome and all animations are still smooth, but in Firefox 33.1.1 it takes at least 7 seconds and degrades transition performance. Test page for 200 and 700 elements + paper-slider with slow animations:\r\nhttp://sysprofile.ru/test.html?count=200\r\nhttp://sysprofile.ru/test.html?count=700\r\n\r\nPolyfills are that much slower than native implementation? Polymer is not working at all with dom.webcomponents.enabled flag..."
}
]
