export default {
  "url": "https://api.github.com/repos/Polymer/polymer/issues/1",
  "labels_url": "https://api.github.com/repos/Polymer/polymer/issues/1/labels{/name}",
  "comments_url": "https://api.github.com/repos/Polymer/polymer/issues/1/comments",
  "events_url": "https://api.github.com/repos/Polymer/polymer/issues/1/events",
  "html_url": "https://github.com/Polymer/polymer/pull/1",
  "id": 7493278,
  "number": 1,
  "title": "Initial Components",
  "user": {
    "login": "sjmiles",
    "id": 98045,
    "avatar_url": "https://avatars.githubusercontent.com/u/98045?v=2",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sjmiles",
    "html_url": "https://github.com/sjmiles",
    "followers_url": "https://api.github.com/users/sjmiles/followers",
    "following_url": "https://api.github.com/users/sjmiles/following{/other_user}",
    "gists_url": "https://api.github.com/users/sjmiles/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sjmiles/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sjmiles/subscriptions",
    "organizations_url": "https://api.github.com/users/sjmiles/orgs",
    "repos_url": "https://api.github.com/users/sjmiles/repos",
    "events_url": "https://api.github.com/users/sjmiles/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sjmiles/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "sorvell",
    "id": 78891,
    "avatar_url": "https://avatars.githubusercontent.com/u/78891?v=2",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sorvell",
    "html_url": "https://github.com/sorvell",
    "followers_url": "https://api.github.com/users/sorvell/followers",
    "following_url": "https://api.github.com/users/sorvell/following{/other_user}",
    "gists_url": "https://api.github.com/users/sorvell/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sorvell/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sorvell/subscriptions",
    "organizations_url": "https://api.github.com/users/sorvell/orgs",
    "repos_url": "https://api.github.com/users/sorvell/repos",
    "events_url": "https://api.github.com/users/sorvell/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sorvell/received_events",
    "type": "User",
    "site_admin": false
  },
  "milestone": null,
  "comments": 0,
  "created_at": "2012-10-10T19:37:06Z",
  "updated_at": "2012-10-10T19:55:53Z",
  "closed_at": "2012-10-10T19:55:53Z",
  "pull_request": {
    "url": "https://api.github.com/repos/Polymer/polymer/pulls/1",
    "html_url": "https://github.com/Polymer/polymer/pull/1",
    "diff_url": "https://github.com/Polymer/polymer/pull/1.diff",
    "patch_url": "https://github.com/Polymer/polymer/pull/1.patch"
  },
  "body": "",
  "closed_by": {
    "login": "sorvell",
    "id": 78891,
    "avatar_url": "https://avatars.githubusercontent.com/u/78891?v=2",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sorvell",
    "html_url": "https://github.com/sorvell",
    "followers_url": "https://api.github.com/users/sorvell/followers",
    "following_url": "https://api.github.com/users/sorvell/following{/other_user}",
    "gists_url": "https://api.github.com/users/sorvell/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sorvell/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sorvell/subscriptions",
    "organizations_url": "https://api.github.com/users/sorvell/orgs",
    "repos_url": "https://api.github.com/users/sorvell/repos",
    "events_url": "https://api.github.com/users/sorvell/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sorvell/received_events",
    "type": "User",
    "site_admin": false
  }
};
